spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lms
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false


server:
  port: 8081